#! /usr/bin/env php
<?php
/**
 * User: Peter Wang
 * Date: 16/10/11
 * Time: 下午6:57
 */
foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('COMPOSER_INSTALL', $file);
        break;
    }
}
$dir = dirname(COMPOSER_INSTALL)."/..";
define("ROOT_PATH", $dir);
require_once COMPOSER_INSTALL;
\Trendi\Foundation\Application::runCmd();