#! /usr/bin/env php
<?php
/**
 * User: Peter Wang
 * Date: 16/9/15
 * Time: 下午10:36
 */
define("ROOT_PATH", __DIR__);
require_once __DIR__ . "/../../vendor/autoload.php";
\Trendi\Foundation\Application::runCmd();